### ISSUE TITLE
u4a deploy tutorial

### ISSUE THREAD

**Issue by 0xff-dev** [kubebb/components#41]
## 1 Intall kubebb/core

首先需要部署基本组件 `kubebb/core`

```shell
helm repo add kubebb https://kubebb.github.io/components
kubectl create ns kubebb-system
helm -nkubebb-system install kubebb/core

NAME                     READY   STATUS    RESTARTS   AGE
kubebb-755784d5f-k8jhh   1/1     Running   0          2m14s
```

## 1.1 create repository

创建包含 `u4a-component` 相关组件的 Repository

```yaml
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Repository
metadata:
  name: kubebb
  namespace: kubebb-system
spec:
  url: http://1.1.1.1:9999/def
  pullStategy:
    intervalSeconds: 120
    retry: 5
```

## 2 cluster-comonent

直接创建 `componentplan`, clustr-component 会部署 `ingress-nginx` 需要选择部署节点名称，默认是`kind-worker`

**注意，这里我们的 namesapce 选择是 u4a-system, 目前不要选择其他的 namespace，适配还不完全**

```yaml
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: cluster-compnent
  namespace: u4a-system
spec:
  approved: true
  name: cluster-component
  version: 0.1.0
  component:
    name: kubebb.cluster-component
    namespace: kubebb-system
```

```shell
root@macbookpro:~/step/components/examples/cluster-component# kubectl get po -nu4a-system 
NAME                                                         READY   STATUS    RESTARTS   AGE
cert-manager-8578d9d85-vbqjj                                 1/1     Running   0          21s
cert-manager-cainjector-786cdfd59b-h2r5x                     1/1     Running   0          22s
cert-manager-webhook-b59474c5d-skvg4                         1/1     Running   0          20s
cluster-component-ingress-nginx-controller-bc5c5f9f5-5mpk4   1/1     Running   0          23s
```

## 3 u4a-component

部署 u4a-comopnent， 需要确定 ingress-node 所在节点名称以及 ip。 
前面部署 `cluster-component` 的时候没有修改 `ingress-nginx` 的部署节点，所以查看 `kind-worker` 节点的 IP 为 `172.18.0.5`

```shell
root@macbookpro:~/step/components/examples/cluster-component# kubectl get node -owide
NAME                 STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
kind-control-plane   Ready    control-plane   49m   v1.24.4   172.18.0.3    <none>        Ubuntu 22.04.1 LTS   5.19.0-46-generic   containerd://1.6.7
kind-worker          Ready    <none>          48m   v1.24.4   172.18.0.5    <none>        Ubuntu 22.04.1 LTS   5.19.0-46-generic   containerd://1.6.7
kind-worker2         Ready    <none>          48m   v1.24.4   172.18.0.4    <none>        Ubuntu 22.04.1 LTS   5.19.0-46-generic   containerd://1.6.7
```

得到 `u4a-compnent` 的 `values.yaml`, 会注意到里面有 `172.18.0.2` 和 `172.18.0.3` 两个 ip。
其中 `172.18.0.2` 需要被替换成 `ingress-nginx` 所在的节点 IP。 同时所有的 `kind-worker` 需要被替换成 ingress-nginx pod 所在的节点名字(当前ingress-nginx也是部署在 `kind-worker` 节点上，所以这里目前可以不做替换)。

`172.18.0.3` 和 `kind-worker2` 这两个是要部署 kube-oidc-proxy 的服务所在的节点 IP 和名称，这个节点目前自己选择即可。

因为 `values.yaml` 改动较多，所以这里将改动后的文件存储在 ConfigMap 中，创建 `Comonent` 的时候通过 `Override` 来指定该 ConfigMap 来修改数据。
根据更改的`values.yaml`创建 configmap

```shell
kubectl -nu4a-system create u4acm --from-file=values.yaml=/path/to/your/values.yaml
```

创建 componentplan 完成 u4a 部署

**注意，这里我们的 namesapce 选择是 u4a-system, 目前不要选择其他的 namespace，适配还不完全**

```shell
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: u4a-component
  namespace: u4a-system
spec:
  approved: true
  name: u4a-component
  version: 0.1.0
  override:
    valuesFrom:
      kind: ConfigMap
      name: u4acm
      valuesKey: "values.yaml"
  component:
    name: kubebb.u4a-component
    namespace: kubebb-system
```

查看 pod

```shell
root@macbookpro:~/step/components/examples/u4a-component# kubectl get po -nu4a-system 
NAME                                                         READY   STATUS    RESTARTS   AGE
bff-server-57449bcbf6-zf7hh                                  1/1     Running   0          2m12s
capsule-controller-manager-68f65d666d-xgcmq                  1/1     Running   0          2m13s
cert-manager-8578d9d85-vbqjj                                 1/1     Running   0          3m52s
cert-manager-cainjector-786cdfd59b-h2r5x                     1/1     Running   0          3m53s
cert-manager-webhook-b59474c5d-skvg4                         1/1     Running   0          3m51s
cluster-component-ingress-nginx-controller-bc5c5f9f5-5mpk4   1/1     Running   0          3m54s
kube-oidc-proxy-58f5fb849b-fvr45                             1/1     Running   0          2m11s
oidc-server-547cfddb77-mws8g                                 2/2     Running   0          2m9s
resource-view-controller-776d6c6b7d-2jg9k                    1/1     Running   0          111s
```

## 4 MinIO

Minio 服务用来存储 合约代码数据，为构建过程提供数据存储。 这里直接通过 `examples/minio/componentplan.yaml` 直接创建即可。

```shell
root@macbookpro:~/step/components/examples/minio# kubectl get po  
NAME             READY   STATUS    RESTARTS   AGE
fabric-minio-0   1/1     Running   0          24s
fabric-minio-1   1/1     Running   0          24s
fabric-minio-2   1/1     Running   0          24s
```

## 5 tekton-operator

直接通过 `exmaples/tekton-operator/componentplan.yaml` 创建即可。

**注意，目前缺少 post-install 的 hook支持，tekton-operator的CRD没有创建出来**

```shell
root@macbookpro:~/step/components/examples/tekton-operator# kubectl get po  
NAME                                                     READY   STATUS    RESTARTS   AGE
fabric-minio-0                                           1/1     Running   0          5h53m
fabric-minio-1                                           1/1     Running   0          5h53m
fabric-minio-2                                           1/1     Running   0          5h53m
fabric-tekton-tekton-operator-766f8795ff-4g55n           2/2     Running   0          19s
fabric-tekton-tekton-operator-webhook-64c8f79546-jrnvd   1/1     Running   0          19s
```

## 6 Fabric-Opertor

Fabric-operator 需要的鸡哥关键参数

1. minio.host

前面在 `default` namespace 下部署了 minio 服务，找到他的 svc 名称和端口 得到 `minio.host` 的值

2. minio.accesskey, minio.secretkey

这两个参数是连接 minio 需要的，通过 minion 服务部署后的secret来获取

```shell
root@macbookpro:~/step/components/examples/minio# kubectl get secret 
NAME           TYPE     DATA   AGE
fabric-minio   Opaque   2      42s
root@macbookpro:~/step/components/examples/minio# kubectl get secret  -oyaml
apiVersion: v1
items:
- apiVersion: v1
  data:
    rootPassword: Z2pLZWg0RkFPRHRla0hlNW1DckRwT0g4d2Q0VTVycDhLa290dDc0WQ==
    rootUser: Q3Q3MTZDMTBkeUI0NERodmZyNDM=
  kind: Secret
  metadata:
    creationTimestamp: "2023-07-06T09:31:39Z"
    labels:
      app: minio
      chart: minio-5.0.7
      core.kubebb.k8s.com.cn/componentplan: fabric-minio
      heritage: Helm
      release: fabric-minio
    name: fabric-minio
    namespace: default
    resourceVersion: "18647"
    uid: 881ed632-1fa9-4514-abf0-fb93a03870e3
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
```

3. dockerhub-secret

我们需要创建一个 secret 名字为 `dockerhub-secret` 用来存储 dockerhub 的认证信息。

```shell
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
data:
  config.json: $(echo -n "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n 'hyperledgerk8stest:Passw0rd!' | base64)\"}}}" | base64 | tr -d \\n)
EOF
```

需要的参数都准备好后，通过下面的 yaml 创建 fabric-operator

**注意，也是当前 post-install 的hook没有实现，admin 用户不会被创建出来，如果要验证 operator 的功能，需要先将 tekton-operator 的CRD 弄起来**

```yaml
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: fabric-operator
  namespace: baas-system
spec:
  approved: true
  name: fabric-operator
  version: 0.1.0
  override:
    set:
    - namespace=baas-system
    - ingressDomain=172.18.0.5.nip.io
    - minio.secretKey=gjKeh4FAODtekHe5mCrDpOH8wd4U5rp8Kkott74Y
    - mino.accessKey=Ct716C10dyB44Dhvfr43
    - minio.host=fabric-minio.default.svc.cluster.local:9000
  component:
    name: kubebb.fabric-operator
    namespace: kubebb-system
```

```shell
root@macbookpro:~/step/components/examples/fabric-operator# kubectl get po -nbaas-system
NAME                                  READY   STATUS    RESTARTS   AGE
controller-manager-595c48b88b-8kz76   1/1     Running   0          36s
```
