### ISSUE TITLE
component charts do not support variable reference 

### ISSUE THREAD

**Issue by bjwswang** [kubebb/components#67]
settings like this won't work in kubebb
```yaml
# Default values for u4a-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# You must check and update the value of each variable below
deploymentConfig:
  # bffServer info
  bffHost: &bffHost
    portal.172.18.0.2.nip.io
```
https://github.com/kubebb/components/blob/main/charts/u4a-component/values.yaml#L8C13-L8C20
